language:
  - python

python:
  - "3.5"

sudo: required

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python3 medical_prescription/manage.py makemigrations
  - python3 medical_prescription/manage.py migrate
  - coverage run python3 medical_prescription/manage.py test

after_success:
  - cd medical_prescription
  - coverage
  - coverage report
  - coveralls
